replicaCount: 2

image:
  repository: 123456789012.dkr.ecr.us-west-2.amazonaws.com/django-prod-repo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

configMap:
  DJANGO_SECRET_KEY: 'django-insecure-for-final-project-only'
  DEBUG: 'True'
  ALLOWED_HOSTS: '*'
  DATABASE_URL: 'sqlite:////tmp/db.sqlite3'

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
